title: Korin Wheaton, Sociology at Whitman College
description: Various Projects
show_downloads: true
google_analytics: 
theme: jekyll-theme-cayman 
plugins:
  - jekyll-include  

# Custom CSS
include:
  - assets/css/styles.css
