title: Korin's projects
description: A dedicated page for my projects
show_downloads: True
google_analytics: 
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
- jekyll-include
