title: Korin Wheaton, Sociology at Whitman College
description: Various Projects
show_downloads: True
google_analytics: 
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 

# Custom CSS
#include:
#  - korinwhe.github.io/assets/css/styles.css
