title: Geolocating Digital Refugees: Twitter User Behavior During Disasters
description: A dedicated page for my project
show_downloads: True
google_analytics: 
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
- jekyll-include
