title: Geolocating Digital Refugees: Twitter User Behavior During Disasters
description: A dedicated page for my project
show_downloads: True
google_analytics: 
theme: jekyll-theme-tactile
plugins:
- jekyll-include
